"""initial schema

Revision ID: 433d2572c38c
Revises: 
Create Date: 2026-03-29 16:17:12.892532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '433d2572c38c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gardens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location_description', sa.Text(), nullable=True),
    sa.Column('last_frost_date', sa.String(length=5), nullable=False),
    sa.Column('first_frost_date', sa.String(length=5), nullable=False),
    sa.Column('layout_pdf_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('garden_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('garden_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'editor', 'viewer', name='member_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['garden_id'], ['gardens.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('garden_seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garden_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('delay_weeks', sa.Integer(), nullable=False),
    sa.Column('delay_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['garden_id'], ['gardens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grow_light_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garden_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('total_tray_capacity', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['garden_id'], ['gardens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('growing_spaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garden_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('raised_bed', 'container', name='space_type'), nullable=False),
    sa.Column('width_ft', sa.Float(), nullable=True),
    sa.Column('length_ft', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['garden_id'], ['gardens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plant_varieties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('common_name', sa.String(length=255), nullable=False),
    sa.Column('latin_name', sa.String(length=255), nullable=True),
    sa.Column('plant_type', sa.Enum('annual', 'perennial', 'biennial', name='plant_type'), nullable=False),
    sa.Column('days_to_germination', sa.Integer(), nullable=True),
    sa.Column('days_to_maturity', sa.String(length=50), nullable=True),
    sa.Column('spacing_inches', sa.Float(), nullable=True),
    sa.Column('sow_depth_inches', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('garden_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garden_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('logged_by_user_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('amount_usd', sa.Float(), nullable=False),
    sa.Column('category', sa.Enum('seeds', 'plants_transplants', 'soil_amendments', 'fertilizer', 'tools_equipment', 'containers', 'pest_disease_control', 'other', name='expense_category'), nullable=False),
    sa.Column('vendor', sa.String(length=255), nullable=True),
    sa.Column('purchased_at', sa.Date(), nullable=True),
    sa.Column('receipt_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['garden_id'], ['gardens.id'], ),
    sa.ForeignKeyConstraint(['logged_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['garden_seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seed_lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variety_id', sa.Integer(), nullable=False),
    sa.Column('lot_number', sa.String(length=100), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('source_vendor', sa.String(length=255), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('quantity_seeds', sa.Integer(), nullable=True),
    sa.Column('germination_rate_pct', sa.Integer(), nullable=True),
    sa.Column('germination_test_date', sa.String(length=10), nullable=True),
    sa.Column('certifications', sa.String(length=500), nullable=True),
    sa.Column('packet_image_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['variety_id'], ['plant_varieties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planting_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('variety_id', sa.Integer(), nullable=False),
    sa.Column('seed_lot_id', sa.Integer(), nullable=True),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.Column('location_note', sa.String(length=255), nullable=True),
    sa.Column('sow_type', sa.Enum('direct', 'indoor_start', name='sow_type'), nullable=False),
    sa.Column('status', sa.Enum('planned', 'active', 'harvested', 'done', 'failed', name='planting_status'), nullable=False),
    sa.Column('planned_sow_date', sa.Date(), nullable=True),
    sa.Column('planned_transplant_date', sa.Date(), nullable=True),
    sa.Column('planned_harvest_start', sa.Date(), nullable=True),
    sa.Column('actual_sow_date', sa.Date(), nullable=True),
    sa.Column('actual_transplant_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('quantity_planted', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['garden_seasons.id'], ),
    sa.ForeignKeyConstraint(['seed_lot_id'], ['seed_lots.id'], ),
    sa.ForeignKeyConstraint(['space_id'], ['growing_spaces.id'], ),
    sa.ForeignKeyConstraint(['variety_id'], ['plant_varieties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grow_light_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('planting_event_id', sa.Integer(), nullable=False),
    sa.Column('tray_type', sa.Enum('cell_32', 'plug_72', name='tray_type'), nullable=False),
    sa.Column('tray_count', sa.Integer(), nullable=False),
    sa.Column('placed_date', sa.Date(), nullable=True),
    sa.Column('removed_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['grow_light_configs.id'], ),
    sa.ForeignKeyConstraint(['planting_event_id'], ['planting_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('harvest_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planting_event_id', sa.Integer(), nullable=False),
    sa.Column('logged_by_user_id', sa.Integer(), nullable=False),
    sa.Column('harvested_at', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.Enum('count', 'lbs', 'oz', 'kg', 'g', 'bunch', name='harvest_unit'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['logged_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['planting_event_id'], ['planting_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issue_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planting_event_id', sa.Integer(), nullable=False),
    sa.Column('logged_by_user_id', sa.Integer(), nullable=False),
    sa.Column('issue_type', sa.Enum('disease', 'pest', 'environmental', 'other', name='issue_type'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', name='issue_severity'), nullable=False),
    sa.Column('occurred_at', sa.Date(), nullable=False),
    sa.Column('resolved_at', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['logged_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['planting_event_id'], ['planting_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planting_event_id', sa.Integer(), nullable=False),
    sa.Column('logged_by_user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('fertilize', 'water', 'prune', 'treat', 'observe', 'other', name='maintenance_type'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('product_used', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['logged_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['planting_event_id'], ['planting_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plant_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planting_event_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=False),
    sa.Column('storage_url', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['planting_event_id'], ['planting_events.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plant_photos')
    op.drop_table('maintenance_logs')
    op.drop_table('issue_logs')
    op.drop_table('harvest_records')
    op.drop_table('grow_light_assignments')
    op.drop_table('planting_events')
    op.drop_table('seed_lots')
    op.drop_table('garden_expenses')
    op.drop_table('plant_varieties')
    op.drop_table('growing_spaces')
    op.drop_table('grow_light_configs')
    op.drop_table('garden_seasons')
    op.drop_table('garden_memberships')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('gardens')
    # ### end Alembic commands ###
